/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package co.com.csj.model.impl;

import co.com.csj.model.Docencia;
import co.com.csj.model.DocenciaModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Docencia service. Represents a row in the &quot;SJ_docencia&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link co.com.csj.model.DocenciaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DocenciaImpl}.
 * </p>
 *
 * @author villartech
 * @see DocenciaImpl
 * @see co.com.csj.model.Docencia
 * @see co.com.csj.model.DocenciaModel
 * @generated
 */
public class DocenciaModelImpl extends BaseModelImpl<Docencia>
	implements DocenciaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a docencia model instance should use the {@link co.com.csj.model.Docencia} interface instead.
	 */
	public static final String TABLE_NAME = "SJ_docencia";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "usuario_fk", Types.VARCHAR },
			{ "fecha_inicial", Types.TIMESTAMP },
			{ "fecha_final", Types.TIMESTAMP },
			{ "materia", Types.VARCHAR },
			{ "institucion", Types.VARCHAR },
			{ "despacho_fk", Types.VARCHAR },
			{ "created_by", Types.BIGINT },
			{ "modified_by", Types.BIGINT },
			{ "estatus", Types.INTEGER },
			{ "horas_docencia", Types.INTEGER },
			{ "minutos_docencia", Types.INTEGER },
			{ "cargo_fk", Types.INTEGER },
			{ "fecha_registro", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table SJ_docencia (ID LONG not null primary key IDENTITY,usuario_fk VARCHAR(75) null,fecha_inicial DATE null,fecha_final DATE null,materia VARCHAR(75) null,institucion VARCHAR(75) null,despacho_fk VARCHAR(75) null,created_by LONG,modified_by LONG,estatus INTEGER,horas_docencia INTEGER,minutos_docencia INTEGER,cargo_fk INTEGER,fecha_registro DATE null)";
	public static final String TABLE_SQL_DROP = "drop table SJ_docencia";
	public static final String ORDER_BY_JPQL = " ORDER BY docencia.id DESC";
	public static final String ORDER_BY_SQL = " ORDER BY SJ_docencia.ID DESC";
	public static final String DATA_SOURCE = "base_despachos";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.co.com.csj.model.Docencia"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.co.com.csj.model.Docencia"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.co.com.csj.model.Docencia"),
			true);
	public static long CREADOPOR_COLUMN_BITMASK = 1L;
	public static long DESPACHO_COLUMN_BITMASK = 2L;
	public static long ESTATUS_COLUMN_BITMASK = 4L;
	public static long USUARIO_FK_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.co.com.csj.model.Docencia"));

	public DocenciaModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Docencia.class;
	}

	public String getModelClassName() {
		return Docencia.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("usuario_fk", getUsuario_fk());
		attributes.put("fechaInicial", getFechaInicial());
		attributes.put("fechaFinal", getFechaFinal());
		attributes.put("materia", getMateria());
		attributes.put("institucion", getInstitucion());
		attributes.put("despacho", getDespacho());
		attributes.put("creadoPor", getCreadoPor());
		attributes.put("modificadoPor", getModificadoPor());
		attributes.put("estatus", getEstatus());
		attributes.put("horas", getHoras());
		attributes.put("minutos", getMinutos());
		attributes.put("cargo", getCargo());
		attributes.put("fechaRegistro", getFechaRegistro());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String usuario_fk = (String)attributes.get("usuario_fk");

		if (usuario_fk != null) {
			setUsuario_fk(usuario_fk);
		}

		Date fechaInicial = (Date)attributes.get("fechaInicial");

		if (fechaInicial != null) {
			setFechaInicial(fechaInicial);
		}

		Date fechaFinal = (Date)attributes.get("fechaFinal");

		if (fechaFinal != null) {
			setFechaFinal(fechaFinal);
		}

		String materia = (String)attributes.get("materia");

		if (materia != null) {
			setMateria(materia);
		}

		String institucion = (String)attributes.get("institucion");

		if (institucion != null) {
			setInstitucion(institucion);
		}

		String despacho = (String)attributes.get("despacho");

		if (despacho != null) {
			setDespacho(despacho);
		}

		Long creadoPor = (Long)attributes.get("creadoPor");

		if (creadoPor != null) {
			setCreadoPor(creadoPor);
		}

		Long modificadoPor = (Long)attributes.get("modificadoPor");

		if (modificadoPor != null) {
			setModificadoPor(modificadoPor);
		}

		Integer estatus = (Integer)attributes.get("estatus");

		if (estatus != null) {
			setEstatus(estatus);
		}

		Integer horas = (Integer)attributes.get("horas");

		if (horas != null) {
			setHoras(horas);
		}

		Integer minutos = (Integer)attributes.get("minutos");

		if (minutos != null) {
			setMinutos(minutos);
		}

		Integer cargo = (Integer)attributes.get("cargo");

		if (cargo != null) {
			setCargo(cargo);
		}

		Date fechaRegistro = (Date)attributes.get("fechaRegistro");

		if (fechaRegistro != null) {
			setFechaRegistro(fechaRegistro);
		}
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getUsuario_fk() {
		if (_usuario_fk == null) {
			return StringPool.BLANK;
		}
		else {
			return _usuario_fk;
		}
	}

	public void setUsuario_fk(String usuario_fk) {
		_columnBitmask |= USUARIO_FK_COLUMN_BITMASK;

		if (_originalUsuario_fk == null) {
			_originalUsuario_fk = _usuario_fk;
		}

		_usuario_fk = usuario_fk;
	}

	public String getOriginalUsuario_fk() {
		return GetterUtil.getString(_originalUsuario_fk);
	}

	public Date getFechaInicial() {
		return _fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		_fechaInicial = fechaInicial;
	}

	public Date getFechaFinal() {
		return _fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		_fechaFinal = fechaFinal;
	}

	public String getMateria() {
		if (_materia == null) {
			return StringPool.BLANK;
		}
		else {
			return _materia;
		}
	}

	public void setMateria(String materia) {
		_materia = materia;
	}

	public String getInstitucion() {
		if (_institucion == null) {
			return StringPool.BLANK;
		}
		else {
			return _institucion;
		}
	}

	public void setInstitucion(String institucion) {
		_institucion = institucion;
	}

	public String getDespacho() {
		if (_despacho == null) {
			return StringPool.BLANK;
		}
		else {
			return _despacho;
		}
	}

	public void setDespacho(String despacho) {
		_columnBitmask |= DESPACHO_COLUMN_BITMASK;

		if (_originalDespacho == null) {
			_originalDespacho = _despacho;
		}

		_despacho = despacho;
	}

	public String getOriginalDespacho() {
		return GetterUtil.getString(_originalDespacho);
	}

	public long getCreadoPor() {
		return _creadoPor;
	}

	public void setCreadoPor(long creadoPor) {
		_columnBitmask |= CREADOPOR_COLUMN_BITMASK;

		if (!_setOriginalCreadoPor) {
			_setOriginalCreadoPor = true;

			_originalCreadoPor = _creadoPor;
		}

		_creadoPor = creadoPor;
	}

	public long getOriginalCreadoPor() {
		return _originalCreadoPor;
	}

	public long getModificadoPor() {
		return _modificadoPor;
	}

	public void setModificadoPor(long modificadoPor) {
		_modificadoPor = modificadoPor;
	}

	public int getEstatus() {
		return _estatus;
	}

	public void setEstatus(int estatus) {
		_columnBitmask |= ESTATUS_COLUMN_BITMASK;

		if (!_setOriginalEstatus) {
			_setOriginalEstatus = true;

			_originalEstatus = _estatus;
		}

		_estatus = estatus;
	}

	public int getOriginalEstatus() {
		return _originalEstatus;
	}

	public int getHoras() {
		return _horas;
	}

	public void setHoras(int horas) {
		_horas = horas;
	}

	public int getMinutos() {
		return _minutos;
	}

	public void setMinutos(int minutos) {
		_minutos = minutos;
	}

	public int getCargo() {
		return _cargo;
	}

	public void setCargo(int cargo) {
		_cargo = cargo;
	}

	public Date getFechaRegistro() {
		return _fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		_fechaRegistro = fechaRegistro;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Docencia.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Docencia toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Docencia)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		DocenciaImpl docenciaImpl = new DocenciaImpl();

		docenciaImpl.setId(getId());
		docenciaImpl.setUsuario_fk(getUsuario_fk());
		docenciaImpl.setFechaInicial(getFechaInicial());
		docenciaImpl.setFechaFinal(getFechaFinal());
		docenciaImpl.setMateria(getMateria());
		docenciaImpl.setInstitucion(getInstitucion());
		docenciaImpl.setDespacho(getDespacho());
		docenciaImpl.setCreadoPor(getCreadoPor());
		docenciaImpl.setModificadoPor(getModificadoPor());
		docenciaImpl.setEstatus(getEstatus());
		docenciaImpl.setHoras(getHoras());
		docenciaImpl.setMinutos(getMinutos());
		docenciaImpl.setCargo(getCargo());
		docenciaImpl.setFechaRegistro(getFechaRegistro());

		docenciaImpl.resetOriginalValues();

		return docenciaImpl;
	}

	public int compareTo(Docencia docencia) {
		int value = 0;

		if (getId() < docencia.getId()) {
			value = -1;
		}
		else if (getId() > docencia.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Docencia docencia = null;

		try {
			docencia = (Docencia)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = docencia.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DocenciaModelImpl docenciaModelImpl = this;

		docenciaModelImpl._originalUsuario_fk = docenciaModelImpl._usuario_fk;

		docenciaModelImpl._originalDespacho = docenciaModelImpl._despacho;

		docenciaModelImpl._originalCreadoPor = docenciaModelImpl._creadoPor;

		docenciaModelImpl._setOriginalCreadoPor = false;

		docenciaModelImpl._originalEstatus = docenciaModelImpl._estatus;

		docenciaModelImpl._setOriginalEstatus = false;

		docenciaModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Docencia> toCacheModel() {
		DocenciaCacheModel docenciaCacheModel = new DocenciaCacheModel();

		docenciaCacheModel.id = getId();

		docenciaCacheModel.usuario_fk = getUsuario_fk();

		String usuario_fk = docenciaCacheModel.usuario_fk;

		if ((usuario_fk != null) && (usuario_fk.length() == 0)) {
			docenciaCacheModel.usuario_fk = null;
		}

		Date fechaInicial = getFechaInicial();

		if (fechaInicial != null) {
			docenciaCacheModel.fechaInicial = fechaInicial.getTime();
		}
		else {
			docenciaCacheModel.fechaInicial = Long.MIN_VALUE;
		}

		Date fechaFinal = getFechaFinal();

		if (fechaFinal != null) {
			docenciaCacheModel.fechaFinal = fechaFinal.getTime();
		}
		else {
			docenciaCacheModel.fechaFinal = Long.MIN_VALUE;
		}

		docenciaCacheModel.materia = getMateria();

		String materia = docenciaCacheModel.materia;

		if ((materia != null) && (materia.length() == 0)) {
			docenciaCacheModel.materia = null;
		}

		docenciaCacheModel.institucion = getInstitucion();

		String institucion = docenciaCacheModel.institucion;

		if ((institucion != null) && (institucion.length() == 0)) {
			docenciaCacheModel.institucion = null;
		}

		docenciaCacheModel.despacho = getDespacho();

		String despacho = docenciaCacheModel.despacho;

		if ((despacho != null) && (despacho.length() == 0)) {
			docenciaCacheModel.despacho = null;
		}

		docenciaCacheModel.creadoPor = getCreadoPor();

		docenciaCacheModel.modificadoPor = getModificadoPor();

		docenciaCacheModel.estatus = getEstatus();

		docenciaCacheModel.horas = getHoras();

		docenciaCacheModel.minutos = getMinutos();

		docenciaCacheModel.cargo = getCargo();

		Date fechaRegistro = getFechaRegistro();

		if (fechaRegistro != null) {
			docenciaCacheModel.fechaRegistro = fechaRegistro.getTime();
		}
		else {
			docenciaCacheModel.fechaRegistro = Long.MIN_VALUE;
		}

		return docenciaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", usuario_fk=");
		sb.append(getUsuario_fk());
		sb.append(", fechaInicial=");
		sb.append(getFechaInicial());
		sb.append(", fechaFinal=");
		sb.append(getFechaFinal());
		sb.append(", materia=");
		sb.append(getMateria());
		sb.append(", institucion=");
		sb.append(getInstitucion());
		sb.append(", despacho=");
		sb.append(getDespacho());
		sb.append(", creadoPor=");
		sb.append(getCreadoPor());
		sb.append(", modificadoPor=");
		sb.append(getModificadoPor());
		sb.append(", estatus=");
		sb.append(getEstatus());
		sb.append(", horas=");
		sb.append(getHoras());
		sb.append(", minutos=");
		sb.append(getMinutos());
		sb.append(", cargo=");
		sb.append(getCargo());
		sb.append(", fechaRegistro=");
		sb.append(getFechaRegistro());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("co.com.csj.model.Docencia");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuario_fk</column-name><column-value><![CDATA[");
		sb.append(getUsuario_fk());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaInicial</column-name><column-value><![CDATA[");
		sb.append(getFechaInicial());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaFinal</column-name><column-value><![CDATA[");
		sb.append(getFechaFinal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>materia</column-name><column-value><![CDATA[");
		sb.append(getMateria());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>institucion</column-name><column-value><![CDATA[");
		sb.append(getInstitucion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>despacho</column-name><column-value><![CDATA[");
		sb.append(getDespacho());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creadoPor</column-name><column-value><![CDATA[");
		sb.append(getCreadoPor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modificadoPor</column-name><column-value><![CDATA[");
		sb.append(getModificadoPor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>estatus</column-name><column-value><![CDATA[");
		sb.append(getEstatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>horas</column-name><column-value><![CDATA[");
		sb.append(getHoras());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>minutos</column-name><column-value><![CDATA[");
		sb.append(getMinutos());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cargo</column-name><column-value><![CDATA[");
		sb.append(getCargo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaRegistro</column-name><column-value><![CDATA[");
		sb.append(getFechaRegistro());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Docencia.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Docencia.class
		};
	private long _id;
	private String _usuario_fk;
	private String _originalUsuario_fk;
	private Date _fechaInicial;
	private Date _fechaFinal;
	private String _materia;
	private String _institucion;
	private String _despacho;
	private String _originalDespacho;
	private long _creadoPor;
	private long _originalCreadoPor;
	private boolean _setOriginalCreadoPor;
	private long _modificadoPor;
	private int _estatus;
	private int _originalEstatus;
	private boolean _setOriginalEstatus;
	private int _horas;
	private int _minutos;
	private int _cargo;
	private Date _fechaRegistro;
	private long _columnBitmask;
	private Docencia _escapedModelProxy;
}