/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package co.com.csj.model.impl;

import co.com.csj.model.tipo_documento;
import co.com.csj.service.tipo_documentoLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the tipo_documento service. Represents a row in the &quot;SJ_tipo_documento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tipo_documentoImpl}.
 * </p>
 *
 * @author villartech
 * @see tipo_documentoImpl
 * @see co.com.csj.model.tipo_documento
 * @generated
 */
public abstract class tipo_documentoBaseImpl extends tipo_documentoModelImpl
	implements tipo_documento {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tipo_documento model instance should use the {@link tipo_documento} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			tipo_documentoLocalServiceUtil.addtipo_documento(this);
		}
		else {
			tipo_documentoLocalServiceUtil.updatetipo_documento(this);
		}
	}
}