/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package co.com.csj.model.impl;

import co.com.csj.model.usuario;
import co.com.csj.model.usuarioModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the usuario service. Represents a row in the &quot;SJ_usuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link co.com.csj.model.usuarioModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link usuarioImpl}.
 * </p>
 *
 * @author villartech
 * @see usuarioImpl
 * @see co.com.csj.model.usuario
 * @see co.com.csj.model.usuarioModel
 * @generated
 */
public class usuarioModelImpl extends BaseModelImpl<usuario>
	implements usuarioModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a usuario model instance should use the {@link co.com.csj.model.usuario} interface instead.
	 */
	public static final String TABLE_NAME = "SJ_usuario";
	public static final Object[][] TABLE_COLUMNS = {
			{ "cedula_id", Types.VARCHAR },
			{ "nombre", Types.VARCHAR },
			{ "apellido", Types.VARCHAR },
			{ "documento_fk", Types.BIGINT },
			{ "despacho_fk", Types.VARCHAR },
			{ "cargo_fk", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table SJ_usuario (cedula_id VARCHAR(75) not null primary key,nombre VARCHAR(75) null,apellido VARCHAR(75) null,documento_fk LONG,despacho_fk VARCHAR(75) null,cargo_fk LONG)";
	public static final String TABLE_SQL_DROP = "drop table SJ_usuario";
	public static final String DATA_SOURCE = "base_despachos";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.co.com.csj.model.usuario"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.co.com.csj.model.usuario"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.co.com.csj.model.usuario"));

	public usuarioModelImpl() {
	}

	public String getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(String primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return usuario.class;
	}

	public String getModelClassName() {
		return usuario.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("nomb", getNomb());
		attributes.put("ape", getApe());
		attributes.put("tipo_doc", getTipo_doc());
		attributes.put("despachofk", getDespachofk());
		attributes.put("cargofk", getCargofk());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String id = (String)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String nomb = (String)attributes.get("nomb");

		if (nomb != null) {
			setNomb(nomb);
		}

		String ape = (String)attributes.get("ape");

		if (ape != null) {
			setApe(ape);
		}

		Long tipo_doc = (Long)attributes.get("tipo_doc");

		if (tipo_doc != null) {
			setTipo_doc(tipo_doc);
		}

		String despachofk = (String)attributes.get("despachofk");

		if (despachofk != null) {
			setDespachofk(despachofk);
		}

		Long cargofk = (Long)attributes.get("cargofk");

		if (cargofk != null) {
			setCargofk(cargofk);
		}
	}

	public String getId() {
		if (_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _id;
		}
	}

	public void setId(String id) {
		_id = id;
	}

	public String getNomb() {
		if (_nomb == null) {
			return StringPool.BLANK;
		}
		else {
			return _nomb;
		}
	}

	public void setNomb(String nomb) {
		_nomb = nomb;
	}

	public String getApe() {
		if (_ape == null) {
			return StringPool.BLANK;
		}
		else {
			return _ape;
		}
	}

	public void setApe(String ape) {
		_ape = ape;
	}

	public long getTipo_doc() {
		return _tipo_doc;
	}

	public void setTipo_doc(long tipo_doc) {
		_tipo_doc = tipo_doc;
	}

	public String getDespachofk() {
		if (_despachofk == null) {
			return StringPool.BLANK;
		}
		else {
			return _despachofk;
		}
	}

	public void setDespachofk(String despachofk) {
		_despachofk = despachofk;
	}

	public long getCargofk() {
		return _cargofk;
	}

	public void setCargofk(long cargofk) {
		_cargofk = cargofk;
	}

	@Override
	public usuario toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (usuario)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		usuarioImpl usuarioImpl = new usuarioImpl();

		usuarioImpl.setId(getId());
		usuarioImpl.setNomb(getNomb());
		usuarioImpl.setApe(getApe());
		usuarioImpl.setTipo_doc(getTipo_doc());
		usuarioImpl.setDespachofk(getDespachofk());
		usuarioImpl.setCargofk(getCargofk());

		usuarioImpl.resetOriginalValues();

		return usuarioImpl;
	}

	public int compareTo(usuario usuario) {
		String primaryKey = usuario.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		usuario usuario = null;

		try {
			usuario = (usuario)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = usuario.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<usuario> toCacheModel() {
		usuarioCacheModel usuarioCacheModel = new usuarioCacheModel();

		usuarioCacheModel.id = getId();

		String id = usuarioCacheModel.id;

		if ((id != null) && (id.length() == 0)) {
			usuarioCacheModel.id = null;
		}

		usuarioCacheModel.nomb = getNomb();

		String nomb = usuarioCacheModel.nomb;

		if ((nomb != null) && (nomb.length() == 0)) {
			usuarioCacheModel.nomb = null;
		}

		usuarioCacheModel.ape = getApe();

		String ape = usuarioCacheModel.ape;

		if ((ape != null) && (ape.length() == 0)) {
			usuarioCacheModel.ape = null;
		}

		usuarioCacheModel.tipo_doc = getTipo_doc();

		usuarioCacheModel.despachofk = getDespachofk();

		String despachofk = usuarioCacheModel.despachofk;

		if ((despachofk != null) && (despachofk.length() == 0)) {
			usuarioCacheModel.despachofk = null;
		}

		usuarioCacheModel.cargofk = getCargofk();

		return usuarioCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", nomb=");
		sb.append(getNomb());
		sb.append(", ape=");
		sb.append(getApe());
		sb.append(", tipo_doc=");
		sb.append(getTipo_doc());
		sb.append(", despachofk=");
		sb.append(getDespachofk());
		sb.append(", cargofk=");
		sb.append(getCargofk());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("co.com.csj.model.usuario");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nomb</column-name><column-value><![CDATA[");
		sb.append(getNomb());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ape</column-name><column-value><![CDATA[");
		sb.append(getApe());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipo_doc</column-name><column-value><![CDATA[");
		sb.append(getTipo_doc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>despachofk</column-name><column-value><![CDATA[");
		sb.append(getDespachofk());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cargofk</column-name><column-value><![CDATA[");
		sb.append(getCargofk());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = usuario.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			usuario.class
		};
	private String _id;
	private String _nomb;
	private String _ape;
	private long _tipo_doc;
	private String _despachofk;
	private long _cargofk;
	private usuario _escapedModelProxy;
}