/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package co.com.csj.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the alerta service. Represents a row in the &quot;SJ_alertas&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link co.com.csj.model.impl.alertaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link co.com.csj.model.impl.alertaImpl}.
 * </p>
 *
 * @author villartech
 * @see alerta
 * @see co.com.csj.model.impl.alertaImpl
 * @see co.com.csj.model.impl.alertaModelImpl
 * @generated
 */
public interface alertaModel extends BaseModel<alerta> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a alerta model instance should use the {@link alerta} interface instead.
	 */

	/**
	 * Returns the primary key of this alerta.
	 *
	 * @return the primary key of this alerta
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this alerta.
	 *
	 * @param primaryKey the primary key of this alerta
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ID of this alerta.
	 *
	 * @return the ID of this alerta
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this alerta.
	 *
	 * @param id the ID of this alerta
	 */
	public void setId(String id);

	/**
	 * Returns the asunto of this alerta.
	 *
	 * @return the asunto of this alerta
	 */
	@AutoEscape
	public String getAsunto();

	/**
	 * Sets the asunto of this alerta.
	 *
	 * @param asunto the asunto of this alerta
	 */
	public void setAsunto(String asunto);

	/**
	 * Returns the mensaje of this alerta.
	 *
	 * @return the mensaje of this alerta
	 */
	@AutoEscape
	public String getMensaje();

	/**
	 * Sets the mensaje of this alerta.
	 *
	 * @param mensaje the mensaje of this alerta
	 */
	public void setMensaje(String mensaje);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(alerta alerta);

	public int hashCode();

	public CacheModel<alerta> toCacheModel();

	public alerta toEscapedModel();

	public String toString();

	public String toXmlString();
}