/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package co.com.csj.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the auditoriaP service. Represents a row in the &quot;SJ_log&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link co.com.csj.model.impl.auditoriaPModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link co.com.csj.model.impl.auditoriaPImpl}.
 * </p>
 *
 * @author villartech
 * @see auditoriaP
 * @see co.com.csj.model.impl.auditoriaPImpl
 * @see co.com.csj.model.impl.auditoriaPModelImpl
 * @generated
 */
public interface auditoriaPModel extends BaseModel<auditoriaP> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a auditoria p model instance should use the {@link auditoriaP} interface instead.
	 */

	/**
	 * Returns the primary key of this auditoria p.
	 *
	 * @return the primary key of this auditoria p
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this auditoria p.
	 *
	 * @param primaryKey the primary key of this auditoria p
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this auditoria p.
	 *
	 * @return the ID of this auditoria p
	 */
	public long getId();

	/**
	 * Sets the ID of this auditoria p.
	 *
	 * @param id the ID of this auditoria p
	 */
	public void setId(long id);

	/**
	 * Returns the tipo_recurso of this auditoria p.
	 *
	 * @return the tipo_recurso of this auditoria p
	 */
	public int getTipo_recurso();

	/**
	 * Sets the tipo_recurso of this auditoria p.
	 *
	 * @param tipo_recurso the tipo_recurso of this auditoria p
	 */
	public void setTipo_recurso(int tipo_recurso);

	/**
	 * Returns the id_recurso_modificado of this auditoria p.
	 *
	 * @return the id_recurso_modificado of this auditoria p
	 */
	@AutoEscape
	public String getId_recurso_modificado();

	/**
	 * Sets the id_recurso_modificado of this auditoria p.
	 *
	 * @param id_recurso_modificado the id_recurso_modificado of this auditoria p
	 */
	public void setId_recurso_modificado(String id_recurso_modificado);

	/**
	 * Returns the tipo_operacion of this auditoria p.
	 *
	 * @return the tipo_operacion of this auditoria p
	 */
	@AutoEscape
	public String getTipo_operacion();

	/**
	 * Sets the tipo_operacion of this auditoria p.
	 *
	 * @param tipo_operacion the tipo_operacion of this auditoria p
	 */
	public void setTipo_operacion(String tipo_operacion);

	/**
	 * Returns the fecha of this auditoria p.
	 *
	 * @return the fecha of this auditoria p
	 */
	public Date getFecha();

	/**
	 * Sets the fecha of this auditoria p.
	 *
	 * @param fecha the fecha of this auditoria p
	 */
	public void setFecha(Date fecha);

	/**
	 * Returns the correo of this auditoria p.
	 *
	 * @return the correo of this auditoria p
	 */
	@AutoEscape
	public String getCorreo();

	/**
	 * Sets the correo of this auditoria p.
	 *
	 * @param correo the correo of this auditoria p
	 */
	public void setCorreo(String correo);

	/**
	 * Returns the usuario_modifico of this auditoria p.
	 *
	 * @return the usuario_modifico of this auditoria p
	 */
	@AutoEscape
	public String getUsuario_modifico();

	/**
	 * Sets the usuario_modifico of this auditoria p.
	 *
	 * @param usuario_modifico the usuario_modifico of this auditoria p
	 */
	public void setUsuario_modifico(String usuario_modifico);

	/**
	 * Returns the modificacion of this auditoria p.
	 *
	 * @return the modificacion of this auditoria p
	 */
	@AutoEscape
	public String getModificacion();

	/**
	 * Sets the modificacion of this auditoria p.
	 *
	 * @param modificacion the modificacion of this auditoria p
	 */
	public void setModificacion(String modificacion);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(auditoriaP auditoriaP);

	public int hashCode();

	public CacheModel<auditoriaP> toCacheModel();

	public auditoriaP toEscapedModel();

	public String toString();

	public String toXmlString();
}