/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package co.com.csj.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the cargo service. Represents a row in the &quot;SJ_cargo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link co.com.csj.model.impl.cargoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link co.com.csj.model.impl.cargoImpl}.
 * </p>
 *
 * @author villartech
 * @see cargo
 * @see co.com.csj.model.impl.cargoImpl
 * @see co.com.csj.model.impl.cargoModelImpl
 * @generated
 */
public interface cargoModel extends BaseModel<cargo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cargo model instance should use the {@link cargo} interface instead.
	 */

	/**
	 * Returns the primary key of this cargo.
	 *
	 * @return the primary key of this cargo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cargo.
	 *
	 * @param primaryKey the primary key of this cargo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the _id of this cargo.
	 *
	 * @return the _id of this cargo
	 */
	public long get_id();

	/**
	 * Sets the _id of this cargo.
	 *
	 * @param _id the _id of this cargo
	 */
	public void set_id(long _id);

	/**
	 * Returns the desc of this cargo.
	 *
	 * @return the desc of this cargo
	 */
	@AutoEscape
	public String getDesc();

	/**
	 * Sets the desc of this cargo.
	 *
	 * @param desc the desc of this cargo
	 */
	public void setDesc(String desc);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(cargo cargo);

	public int hashCode();

	public CacheModel<cargo> toCacheModel();

	public cargo toEscapedModel();

	public String toString();

	public String toXmlString();
}