/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package co.com.csj.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the licencia_permiso service. Represents a row in the &quot;SJ_licencia_permiso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link co.com.csj.model.impl.licencia_permisoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link co.com.csj.model.impl.licencia_permisoImpl}.
 * </p>
 *
 * @author villartech
 * @see licencia_permiso
 * @see co.com.csj.model.impl.licencia_permisoImpl
 * @see co.com.csj.model.impl.licencia_permisoModelImpl
 * @generated
 */
public interface licencia_permisoModel extends BaseModel<licencia_permiso> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a licencia_permiso model instance should use the {@link licencia_permiso} interface instead.
	 */

	/**
	 * Returns the primary key of this licencia_permiso.
	 *
	 * @return the primary key of this licencia_permiso
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this licencia_permiso.
	 *
	 * @param primaryKey the primary key of this licencia_permiso
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this licencia_permiso.
	 *
	 * @return the ID of this licencia_permiso
	 */
	public long getId();

	/**
	 * Sets the ID of this licencia_permiso.
	 *
	 * @param id the ID of this licencia_permiso
	 */
	public void setId(long id);

	/**
	 * Returns the fechainicio of this licencia_permiso.
	 *
	 * @return the fechainicio of this licencia_permiso
	 */
	public Date getFechainicio();

	/**
	 * Sets the fechainicio of this licencia_permiso.
	 *
	 * @param fechainicio the fechainicio of this licencia_permiso
	 */
	public void setFechainicio(Date fechainicio);

	/**
	 * Returns the fechafin of this licencia_permiso.
	 *
	 * @return the fechafin of this licencia_permiso
	 */
	public Date getFechafin();

	/**
	 * Sets the fechafin of this licencia_permiso.
	 *
	 * @param fechafin the fechafin of this licencia_permiso
	 */
	public void setFechafin(Date fechafin);

	/**
	 * Returns the usuariofk of this licencia_permiso.
	 *
	 * @return the usuariofk of this licencia_permiso
	 */
	@AutoEscape
	public String getUsuariofk();

	/**
	 * Sets the usuariofk of this licencia_permiso.
	 *
	 * @param usuariofk the usuariofk of this licencia_permiso
	 */
	public void setUsuariofk(String usuariofk);

	/**
	 * Returns the tipofk of this licencia_permiso.
	 *
	 * @return the tipofk of this licencia_permiso
	 */
	public long getTipofk();

	/**
	 * Sets the tipofk of this licencia_permiso.
	 *
	 * @param tipofk the tipofk of this licencia_permiso
	 */
	public void setTipofk(long tipofk);

	/**
	 * Returns the actoadmin of this licencia_permiso.
	 *
	 * @return the actoadmin of this licencia_permiso
	 */
	@AutoEscape
	public String getActoadmin();

	/**
	 * Sets the actoadmin of this licencia_permiso.
	 *
	 * @param actoadmin the actoadmin of this licencia_permiso
	 */
	public void setActoadmin(String actoadmin);

	/**
	 * Returns the creado por of this licencia_permiso.
	 *
	 * @return the creado por of this licencia_permiso
	 */
	public long getCreadoPor();

	/**
	 * Sets the creado por of this licencia_permiso.
	 *
	 * @param creadoPor the creado por of this licencia_permiso
	 */
	public void setCreadoPor(long creadoPor);

	/**
	 * Returns the modificado por of this licencia_permiso.
	 *
	 * @return the modificado por of this licencia_permiso
	 */
	public long getModificadoPor();

	/**
	 * Sets the modificado por of this licencia_permiso.
	 *
	 * @param modificadoPor the modificado por of this licencia_permiso
	 */
	public void setModificadoPor(long modificadoPor);

	/**
	 * Returns the estatus of this licencia_permiso.
	 *
	 * @return the estatus of this licencia_permiso
	 */
	public int getEstatus();

	/**
	 * Sets the estatus of this licencia_permiso.
	 *
	 * @param estatus the estatus of this licencia_permiso
	 */
	public void setEstatus(int estatus);

	/**
	 * Returns the despacho of this licencia_permiso.
	 *
	 * @return the despacho of this licencia_permiso
	 */
	@AutoEscape
	public String getDespacho();

	/**
	 * Sets the despacho of this licencia_permiso.
	 *
	 * @param despacho the despacho of this licencia_permiso
	 */
	public void setDespacho(String despacho);

	/**
	 * Returns the cargo of this licencia_permiso.
	 *
	 * @return the cargo of this licencia_permiso
	 */
	public int getCargo();

	/**
	 * Sets the cargo of this licencia_permiso.
	 *
	 * @param cargo the cargo of this licencia_permiso
	 */
	public void setCargo(int cargo);

	/**
	 * Returns the horas of this licencia_permiso.
	 *
	 * @return the horas of this licencia_permiso
	 */
	public int getHoras();

	/**
	 * Sets the horas of this licencia_permiso.
	 *
	 * @param horas the horas of this licencia_permiso
	 */
	public void setHoras(int horas);

	/**
	 * Returns the minutos of this licencia_permiso.
	 *
	 * @return the minutos of this licencia_permiso
	 */
	public int getMinutos();

	/**
	 * Sets the minutos of this licencia_permiso.
	 *
	 * @param minutos the minutos of this licencia_permiso
	 */
	public void setMinutos(int minutos);

	/**
	 * Returns the fecha registro of this licencia_permiso.
	 *
	 * @return the fecha registro of this licencia_permiso
	 */
	public Date getFechaRegistro();

	/**
	 * Sets the fecha registro of this licencia_permiso.
	 *
	 * @param fechaRegistro the fecha registro of this licencia_permiso
	 */
	public void setFechaRegistro(Date fechaRegistro);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(licencia_permiso licencia_permiso);

	public int hashCode();

	public CacheModel<licencia_permiso> toCacheModel();

	public licencia_permiso toEscapedModel();

	public String toString();

	public String toXmlString();
}