/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package co.com.csj.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the usuario service. Represents a row in the &quot;SJ_usuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link co.com.csj.model.impl.usuarioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link co.com.csj.model.impl.usuarioImpl}.
 * </p>
 *
 * @author villartech
 * @see usuario
 * @see co.com.csj.model.impl.usuarioImpl
 * @see co.com.csj.model.impl.usuarioModelImpl
 * @generated
 */
public interface usuarioModel extends BaseModel<usuario> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a usuario model instance should use the {@link usuario} interface instead.
	 */

	/**
	 * Returns the primary key of this usuario.
	 *
	 * @return the primary key of this usuario
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this usuario.
	 *
	 * @param primaryKey the primary key of this usuario
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ID of this usuario.
	 *
	 * @return the ID of this usuario
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this usuario.
	 *
	 * @param id the ID of this usuario
	 */
	public void setId(String id);

	/**
	 * Returns the nomb of this usuario.
	 *
	 * @return the nomb of this usuario
	 */
	@AutoEscape
	public String getNomb();

	/**
	 * Sets the nomb of this usuario.
	 *
	 * @param nomb the nomb of this usuario
	 */
	public void setNomb(String nomb);

	/**
	 * Returns the ape of this usuario.
	 *
	 * @return the ape of this usuario
	 */
	@AutoEscape
	public String getApe();

	/**
	 * Sets the ape of this usuario.
	 *
	 * @param ape the ape of this usuario
	 */
	public void setApe(String ape);

	/**
	 * Returns the tipo_doc of this usuario.
	 *
	 * @return the tipo_doc of this usuario
	 */
	public long getTipo_doc();

	/**
	 * Sets the tipo_doc of this usuario.
	 *
	 * @param tipo_doc the tipo_doc of this usuario
	 */
	public void setTipo_doc(long tipo_doc);

	/**
	 * Returns the despachofk of this usuario.
	 *
	 * @return the despachofk of this usuario
	 */
	@AutoEscape
	public String getDespachofk();

	/**
	 * Sets the despachofk of this usuario.
	 *
	 * @param despachofk the despachofk of this usuario
	 */
	public void setDespachofk(String despachofk);

	/**
	 * Returns the cargofk of this usuario.
	 *
	 * @return the cargofk of this usuario
	 */
	public long getCargofk();

	/**
	 * Sets the cargofk of this usuario.
	 *
	 * @param cargofk the cargofk of this usuario
	 */
	public void setCargofk(long cargofk);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(usuario usuario);

	public int hashCode();

	public CacheModel<usuario> toCacheModel();

	public usuario toEscapedModel();

	public String toString();

	public String toXmlString();
}